Repository Team-Digimon/muzusi-was, pull requests merged in 2024-12, with the labels that each got.

#6 Feature: Swagger 설정
  build.gradle
  src/main/java/muzusi/config/SwaggerConfig.java
Labels: enhancement

#9 Chore: cd 설정
  .github/workflows/cd.yml
  Dockerfile
Labels: chore

#10 Feature: 글로벌 예외처리 및 HTTP 반환값 설정
  Dockerfile
  src/main/java/muzusi/domain/post/exception/PostErrorType.java
  src/main/java/muzusi/domain/stock/exception/StockErrorType.java
  src/main/java/muzusi/domain/user/exception/UserErrorType.java
  src/main/java/muzusi/global/exception/CustomException.java
  src/main/java/muzusi/global/exception/GlobalExceptionHandler.java
  src/main/java/muzusi/global/response/error/ErrorResponse.java
  src/main/java/muzusi/global/response/error/type/BaseErrorType.java
  src/main/java/muzusi/global/response/error/type/CommonErrorType.java
  src/main/java/muzusi/global/response/success/SuccessResponse.java
  src/main/java/muzusi/global/response/success/type/SuccessType.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#13 Feature: Spring Security 설정
  build.gradle
  src/main/java/muzusi/config/SecurityConfig.java
  src/main/java/muzusi/domain/user/repository/UserRepository.java
  src/main/java/muzusi/domain/user/service/UserService.java
  src/main/java/muzusi/global/security/auth/CustomUserDetails.java
  src/main/java/muzusi/global/security/auth/UserDetailsServiceImpl.java
Labels: feat

#15 Chore: DDD 방식 패키지 설정
  src/main/java/muzusi/application/.gitkeep
  src/main/java/muzusi/infrastructure/config/JpaConfig.java
  src/main/java/muzusi/infrastructure/config/SwaggerConfig.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/infrastructure/config/security/SecurityFilterConfig.java
  src/main/java/muzusi/presentation/.gitkeep
Labels: chore

#18 Feature: OAuth 연동
  src/main/java/muzusi/application/.gitkeep
  src/main/java/muzusi/application/auth/dto/LoginDto.java
  src/main/java/muzusi/application/auth/dto/OAuthCodeDto.java
  src/main/java/muzusi/application/auth/dto/UserInfoDto.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/application/auth/service/client/KakaoClient.java
  src/main/java/muzusi/application/auth/service/client/NaverClient.java
  src/main/java/muzusi/application/auth/service/client/OAuthClient.java
  src/main/java/muzusi/application/auth/service/client/OAuthClientFactory.java
  src/main/java/muzusi/domain/user/entity/User.java
  src/main/java/muzusi/domain/user/exception/UserErrorType.java
  src/main/java/muzusi/domain/user/repository/UserRepository.java
  src/main/java/muzusi/domain/user/service/UserService.java
  src/main/java/muzusi/domain/user/type/OAuthPlatform.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/infrastructure/properties/KakaoProperties.java
  src/main/java/muzusi/infrastructure/properties/NaverProperties.java
  src/main/java/muzusi/presentation/.gitkeep
  src/main/java/muzusi/presentation/auth/Controller/AuthController.java
  src/main/resources/application.yml
Labels: feat

#19 Fix: Swagger 버전 최신화
  build.gradle
Labels: fix

#21 Feautre: Login 과정 구현
  src/main/java/muzusi/application/auth/dto/LoginDto.java
  src/main/java/muzusi/application/auth/dto/OAuthCodeDto.java
  src/main/java/muzusi/application/auth/dto/TokenDto.java
  src/main/java/muzusi/application/auth/dto/UserStatusDto.java
  src/main/java/muzusi/application/auth/helper/JwtHelper.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/application/auth/service/client/KakaoClient.java
  src/main/java/muzusi/application/auth/service/client/NaverClient.java
  src/main/java/muzusi/application/auth/service/client/OAuthClient.java
  src/main/java/muzusi/global/util/cookie/CookieUtil.java
  src/main/java/muzusi/global/util/jwt/AuthConstants.java
  src/main/java/muzusi/infrastructure/config/CorsConfig.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/presentation/auth/Controller/AuthController.java
  src/main/java/muzusi/presentation/auth/api/AuthApi.java
  src/main/java/muzusi/presentation/auth/controller/AuthController.java
Labels: feat

#22 Fix: 에러 코드 응답 시 출력 오류로 인한 수정
  src/main/java/muzusi/domain/post/exception/PostErrorType.java
  src/main/java/muzusi/domain/stock/exception/StockErrorType.java
  src/main/java/muzusi/domain/user/exception/UserErrorType.java
  src/main/java/muzusi/global/response/error/ErrorResponse.java
  src/main/java/muzusi/global/response/error/type/BaseErrorType.java
  src/main/java/muzusi/global/response/error/type/CommonErrorType.java
Labels: fix

#23 Chore: API-Link-Checker 라이브러리 연결
  build.gradle
  src/main/java/muzusi/infrastructure/config/ApiLinkCheckerConfig.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/presentation/auth/api/AuthApi.java
  src/main/resources/application.yml
Labels: chore

#24 Feature: refresh token 및 로그아웃 구현
  src/main/java/muzusi/application/auth/helper/JwtHelper.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/application/auth/service/token/RefreshTokenService.java
  src/main/java/muzusi/global/redis/RedisService.java
  src/main/java/muzusi/global/response/error/type/CommonErrorType.java
  src/main/java/muzusi/infrastructure/config/RedisConfig.java
  src/main/java/muzusi/presentation/auth/api/AuthApi.java
  src/main/java/muzusi/presentation/auth/controller/AuthController.java
  src/main/resources/application.yml
Labels: feat

#26 Feature: 회원가입 구현
  src/main/java/muzusi/application/auth/dto/SignUpDto.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/application/auth/service/client/KakaoClient.java
  src/main/java/muzusi/application/auth/service/client/NaverClient.java
  src/main/java/muzusi/application/auth/service/client/OAuthClient.java
  src/main/java/muzusi/domain/user/entity/User.java
  src/main/java/muzusi/domain/user/exception/UserErrorType.java
  src/main/java/muzusi/domain/user/service/UserService.java
  src/main/java/muzusi/presentation/auth/api/AuthApi.java
  src/main/java/muzusi/presentation/auth/controller/AuthController.java
Labels: feat

#27 Chore: MongoDB 연결 및 기초 설정
  build.gradle
  src/main/java/muzusi/infrastructure/config/MongoConfig.java
  src/main/java/muzusi/infrastructure/properties/MongoProperties.java
  src/main/resources/application.yml
Labels: chore

#28 Fix: Replica Set 미적용에 따른 Transaction 설정 코드 삭제
  src/main/java/muzusi/infrastructure/config/MongoConfig.java
Labels: fix

#30 Feature: News API 연결 및 스케쥴러 적용
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/application/auth/service/OAuthClientFactory.java
  src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
  src/main/java/muzusi/application/news/service/NewsService.java
  src/main/java/muzusi/domain/post/entity/Post.java
  src/main/java/muzusi/domain/post/repository/PostRepository.java
  src/main/java/muzusi/domain/post/service/PostService.java
  src/main/java/muzusi/global/util/datetime/DateTimeFormatterUtil.java
  src/main/java/muzusi/infrastructure/news/NewsApiClient.java
  src/main/java/muzusi/infrastructure/oauth/KakaoClient.java
  src/main/java/muzusi/infrastructure/oauth/NaverClient.java
  src/main/java/muzusi/infrastructure/oauth/OAuthClient.java
  src/main/java/muzusi/infrastructure/properties/NewsProperties.java
  src/main/resources/application.yml
Labels: feat
