Repository Team-Digimon/muzusi-was, pull requests merged in 2025-01, with the labels that each got.

#32 Feature: 한국투자증권 인증 API 연결
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/kis/service/KisOAuthService.java
  src/main/java/muzusi/global/redis/RedisService.java
  src/main/java/muzusi/infrastructure/kis/KisConstant.java
  src/main/java/muzusi/infrastructure/kis/KisOAuthClient.java
  src/main/java/muzusi/infrastructure/kis/KisUrlConstant.java
  src/main/java/muzusi/infrastructure/properties/KisProperties.java
  src/main/resources/application.yml
Labels: feat

#33 Feature: 뉴스 조회 로직 구현
  src/main/java/muzusi/application/news/dto/NewsInfoDto.java
  src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
  src/main/java/muzusi/application/news/service/NewsManagementService.java
  src/main/java/muzusi/application/news/service/NewsSearchService.java
  src/main/java/muzusi/domain/news/entity/News.java
  src/main/java/muzusi/domain/news/exception/NewsErrorType.java
  src/main/java/muzusi/domain/news/repository/NewsRepository.java
  src/main/java/muzusi/domain/news/service/NewsService.java
  src/main/java/muzusi/domain/news/type/KeywordType.java
  src/main/java/muzusi/domain/post/repository/PostRepository.java
  src/main/java/muzusi/domain/post/service/PostService.java
  src/main/java/muzusi/global/response/success/SuccessResponse.java
  src/main/java/muzusi/infrastructure/config/PageConfig.java
  src/main/java/muzusi/presentation/news/api/NewsApi.java
  src/main/java/muzusi/presentation/news/controller/NewsController.java
Labels: feat

#34 Feature: 뉴스 삭제 스케쥴러 구현
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
  src/main/java/muzusi/application/news/service/NewsManagementService.java
  src/main/java/muzusi/domain/news/repository/NewsRepository.java
  src/main/java/muzusi/domain/news/service/NewsService.java
  src/main/java/muzusi/infrastructure/config/SchedulingConfig.java
Labels: feat

#35 Refact: 공통된 로직 리팩토링 및 불필요 의존성 삭제
  src/main/java/muzusi/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/muzusi/infrastructure/config/security/SecurityFilterConfig.java
  src/main/java/muzusi/infrastructure/oauth/KakaoClient.java
  src/main/java/muzusi/infrastructure/oauth/NaverClient.java
  src/main/java/muzusi/infrastructure/oauth/OAuthClient.java
  src/main/java/muzusi/infrastructure/oauth/OAuthService.java
  src/main/java/muzusi/infrastructure/properties/KakaoProperties.java
  src/main/java/muzusi/infrastructure/properties/NaverProperties.java
  src/main/java/muzusi/infrastructure/properties/OAuthProperties.java
  src/main/resources/application.yml
Labels: refact

#37 Feature: Stock Entity 필드 추가
  src/main/java/muzusi/domain/stock/entity/Stock.java
  src/main/java/muzusi/domain/stock/type/MarketType.java
Labels: feat

#41 Feature: 계좌 생성 로직 구현
  src/main/java/muzusi/application/account/service/AccountManagementService.java
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/domain/user/entity/User.java
  src/main/java/muzusi/global/response/success/SuccessResponse.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
  src/main/java/muzusi/presentation/account/controller/AccountController.java
Labels: feat

#39 Feature: 한국투자증권 거래량 순위 API 연결
  src/main/java/muzusi/application/kis/dto/KisAuthDto.java
  src/main/java/muzusi/application/kis/service/KisOAuthService.java
  src/main/java/muzusi/application/kis/service/KisRankingService.java
  src/main/java/muzusi/application/stock/dto/RankStockDto.java
  src/main/java/muzusi/application/stock/service/StockService.java
  src/main/java/muzusi/domain/stock/repository/StockRepository.java
  src/main/java/muzusi/global/redis/RedisService.java
  src/main/java/muzusi/infrastructure/kis/KisConstant.java
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
  src/main/java/muzusi/infrastructure/kis/KisUrlConstant.java
Labels: feat

#42 Feature: 계좌 전체 불러오기 및 최신 계좌 불러오기
  build.gradle
  src/main/java/muzusi/application/account/dto/AccountInfoDto.java
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/domain/account/entity/Account.java
  src/main/java/muzusi/domain/account/exception/AccountErrorType.java
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
  src/main/java/muzusi/presentation/account/controller/AccountController.java
Labels: feat

#45 Feature: 주식 매수/매도 로직 구현
  src/main/java/muzusi/application/stock/service/StockService.java
  src/main/java/muzusi/application/trade/dto/TradeReqDto.java
  src/main/java/muzusi/application/trade/service/StockTradeService.java
  src/main/java/muzusi/domain/stock/exception/StockErrorType.java
  src/main/java/muzusi/domain/stock/repository/StockRepository.java
  src/main/java/muzusi/domain/trade/entity/Trade.java
  src/main/java/muzusi/domain/trade/repository/TradeRepository.java
  src/main/java/muzusi/domain/trade/service/TradeService.java
  src/main/java/muzusi/domain/trade/type/TradeType.java
  src/main/java/muzusi/presentation/trade/api/TradeApi.java
  src/main/java/muzusi/presentation/trade/controller/TradeController.java
Labels: feat

#46 Feature: 한국투자증권 등락률 순위 API 연결
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/kis/service/KisRankingService.java
  src/main/java/muzusi/application/stock/dto/RankStockDto.java
  src/main/java/muzusi/infrastructure/kis/KisConstant.java
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
  src/main/java/muzusi/infrastructure/kis/KisUrlConstant.java
Labels: feat

#47 Feature: 주식 거래 분기에 따른 처리
  src/main/java/muzusi/application/account/service/AccountManagementService.java
  src/main/java/muzusi/application/trade/dto/TradeReqDto.java
  src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
  src/main/java/muzusi/application/trade/service/StockTradeService.java
  src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
  src/main/java/muzusi/domain/account/entity/Account.java
  src/main/java/muzusi/domain/trade/entity/TradeReservation.java
  src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/main/java/muzusi/infrastructure/config/MongoConfig.java
Labels: feat

#48 Feature: Jwt Payload 정보 추가
  src/main/java/muzusi/application/auth/dto/SignUpDto.java
  src/main/java/muzusi/application/auth/helper/JwtHelper.java
  src/main/java/muzusi/application/auth/service/AuthService.java
  src/main/java/muzusi/global/security/jwt/JwtProvider.java
  src/main/java/muzusi/presentation/auth/api/AuthApi.java
  src/main/java/muzusi/presentation/auth/controller/AuthController.java
Labels: feat

#53 Feature: 외부 API 에러 알림을 위한 Discord Webhook 적용
  src/main/java/muzusi/application/kis/service/KisOAuthService.java
  src/main/java/muzusi/global/aop/ExternalApiExceptionAspectForDev.java
  src/main/java/muzusi/global/aop/ExternalApiExceptionAspectForProd.java
  src/main/java/muzusi/global/exception/KisOAuthApiException.java
  src/main/java/muzusi/infrastructure/config/AsyncConfig.java
  src/main/java/muzusi/infrastructure/kis/KisOAuthClient.java
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
  src/main/java/muzusi/infrastructure/properties/DiscordWebhookProperties.java
  src/main/java/muzusi/infrastructure/webhook/DiscordWebhookClient.java
  src/main/java/muzusi/infrastructure/webhook/Embed.java
  src/main/java/muzusi/infrastructure/webhook/Message.java
  src/main/resources/application.yml
Labels: feat

#57 Feature: 주식 순위 조회 API
  src/main/java/muzusi/application/kis/service/KisRankingService.java
  src/main/java/muzusi/application/stock/service/StockRankingService.java
  src/main/java/muzusi/domain/stock/type/StockRankingType.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/presentation/stock/api/StockRankingApi.java
  src/main/java/muzusi/presentation/stock/controller/StockRankingController.java
Labels: feat

#58 Feature: 예약 매수 계좌 금액 처리 및 예외 로직 수정
  src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
  src/main/java/muzusi/application/trade/service/StockTradeService.java
  src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
  src/main/java/muzusi/domain/account/entity/Account.java
  src/main/java/muzusi/domain/holding/entity/Holding.java
  src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
  src/test/java/muzusi/application/trade/service/StockTradeServiceTest.java
  src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java
Labels: feat

#59 Feature: 무분별한 계좌 개설 제한
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/domain/account/exception/AccountErrorType.java
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
Labels: feat

#61 Feature: 주식 거래 예약 취소 구현
  src/main/java/muzusi/application/trade/service/StockTradeService.java
  src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
  src/main/java/muzusi/domain/trade/exception/TradeErrorType.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/main/java/muzusi/presentation/trade/api/TradeApi.java
  src/main/java/muzusi/presentation/trade/controller/TradeController.java
  src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java
Labels: feat

#62 Refact: News 로직 수정 및 Security Endpoint 허용
  src/main/java/muzusi/application/news/dto/NewsInfoDto.java
  src/main/java/muzusi/application/news/service/NewsManagementService.java
  src/main/java/muzusi/domain/news/repository/NewsRepository.java
  src/main/java/muzusi/domain/news/service/NewsService.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
Labels: refact

#63 Fix: 공휴일 간 주식 순위 저장 시 오류로 인한 변경
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
Labels: fix

#65 Feature: 주식 차트 기간별 조회 구현
  src/main/java/muzusi/application/stock/dto/StockChartInfoDto.java
  src/main/java/muzusi/application/stock/service/StockHistoryService.java
  src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
  src/main/java/muzusi/domain/stock/entity/StockDaily.java
  src/main/java/muzusi/domain/stock/entity/StockMonthly.java
  src/main/java/muzusi/domain/stock/entity/StockWeekly.java
  src/main/java/muzusi/domain/stock/entity/StockYearly.java
  src/main/java/muzusi/domain/stock/repository/StockDailyRepository.java
  src/main/java/muzusi/domain/stock/repository/StockMonthlyRepository.java
  src/main/java/muzusi/domain/stock/repository/StockWeeklyRepository.java
  src/main/java/muzusi/domain/stock/repository/StockYearlyRepository.java
  src/main/java/muzusi/domain/stock/service/StockDailyService.java
  src/main/java/muzusi/domain/stock/service/StockMonthlyService.java
  src/main/java/muzusi/domain/stock/service/StockService.java
  src/main/java/muzusi/domain/stock/service/StockWeeklyService.java
  src/main/java/muzusi/domain/stock/service/StockYearlyService.java
  src/main/java/muzusi/domain/stock/type/StockPeriodType.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/presentation/stock/api/StockHistoryApi.java
  src/main/java/muzusi/presentation/stock/controller/StockHistoryController.java
  src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
Labels: feat

#66 Feature: 주식 순위 갱신 시간 저장
  src/main/java/muzusi/application/kis/dto/KisDto.java
  src/main/java/muzusi/application/kis/service/KisRankingService.java
  src/main/java/muzusi/application/stock/service/StockRankingService.java
  src/main/java/muzusi/global/redis/RedisService.java
  src/main/java/muzusi/infrastructure/kis/KisConstant.java
  src/main/java/muzusi/presentation/stock/api/StockRankingApi.java
Labels: feat

#67 Feature: 계좌 거래내역 조회 및 Trade 필드 수정
  src/main/java/muzusi/application/account/dto/AccountInfoDto.java
  src/main/java/muzusi/application/account/dto/TradeInfoDto.java
  src/main/java/muzusi/application/account/service/TradeHistoryService.java
  src/main/java/muzusi/application/trade/dto/TradeReqDto.java
  src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
  src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
  src/main/java/muzusi/domain/account/exception/AccountErrorType.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/domain/trade/entity/Trade.java
  src/main/java/muzusi/domain/trade/entity/TradeReservation.java
  src/main/java/muzusi/domain/trade/repository/TradeRepository.java
  src/main/java/muzusi/domain/trade/service/TradeService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
  src/main/java/muzusi/presentation/account/controller/AccountController.java
  src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
  src/test/java/muzusi/application/trade/service/StockTradeServiceTest.java
  src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java
Labels: feat

#69 Feature: 주식 검색어 자동완성 구현
  src/main/java/muzusi/application/stock/dto/StockItemDto.java
  src/main/java/muzusi/application/stock/service/StockHistoryService.java
  src/main/java/muzusi/application/stock/service/StockSearchService.java
  src/main/java/muzusi/domain/stock/entity/StockItem.java
  src/main/java/muzusi/domain/stock/repository/StockItemCustomRepository.java
  src/main/java/muzusi/domain/stock/repository/StockItemCustomRepositoryImpl.java
  src/main/java/muzusi/domain/stock/repository/StockItemRepository.java
  src/main/java/muzusi/domain/stock/service/StockItemService.java
  src/main/java/muzusi/presentation/stock/api/StockApi.java
  src/main/java/muzusi/presentation/stock/controller/StockController.java
Labels: feat

#70 Feature: 장 마감 시, 예약 내역 삭제 로직 구현
  src/main/java/muzusi/application/trade/scheduler/TradeScheduler.java
  src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
  src/main/java/muzusi/application/trade/service/TradeReservationCleaner.java
  src/main/java/muzusi/domain/holding/entity/Holding.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/test/java/muzusi/application/trade/service/TradeReservationCleanerTest.java
Labels: feat
