Repository Team-Digimon/muzusi-was, pull requests merged in 2025-02, with the labels that each got.

#73 Feature: 스케줄링 전용 쓰레드풀 설정
  src/main/java/muzusi/infrastructure/config/SchedulingConfig.java
Labels: feat

#71 Feature: 주식 예약 내역 성공 처리 로직 구현
  src/main/java/muzusi/application/trade/service/TradeReservationTrigger.java
  src/main/java/muzusi/domain/holding/entity/Holding.java
  src/main/java/muzusi/domain/holding/service/HoldingService.java
  src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/test/java/muzusi/application/trade/service/TradeReservationTriggerTest.java
Labels: feat

#75 Feature: 예약한 주식 정보 반환 기능 추가
  src/main/java/muzusi/application/trade/dto/ReservationInfoDto.java
  src/main/java/muzusi/application/trade/service/UserTradeReservationService.java
  src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/main/java/muzusi/presentation/trade/api/TradeReservationApi.java
  src/main/java/muzusi/presentation/trade/controller/TradeReservationController.java
Labels: feat

#76 Feature: 계좌 개설 가능 시간 설정
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/domain/account/exception/AccountErrorType.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
Labels: feat

#81 Feature: 주식 분봉 데이터 저장
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
  src/main/java/muzusi/application/kis/service/KisStockService.java
  src/main/java/muzusi/domain/stock/entity/StockMinutes.java
  src/main/java/muzusi/domain/stock/repository/StockMinutesRepository.java
  src/main/java/muzusi/domain/stock/service/StockMinutesService.java
Labels: feat

#83 Feature: 주식 현재가 저장
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
  src/main/java/muzusi/application/stock/dto/StockPriceDto.java
  src/main/java/muzusi/infrastructure/config/RedisConfig.java
  src/main/java/muzusi/infrastructure/redis/RedisService.java
  src/main/java/muzusi/infrastructure/redis/constant/KisConstant.java
Labels: feat

#84 Feature: 예약 내역 확인 처리 스케줄링 적용
  src/main/java/muzusi/application/trade/scheduler/TradeScheduler.java
  src/main/java/muzusi/application/trade/service/TradeReservationProcessor.java
  src/main/java/muzusi/application/trade/service/TradeReservationTrigger.java
  src/main/java/muzusi/infrastructure/redis/RedisService.java
  src/test/java/muzusi/application/trade/service/TradeReservationProcessorTest.java
  src/test/java/muzusi/application/trade/service/TradeReservationTriggerTest.java
Labels: feat

#87 Feature: 계좌 및 보유 주식별 수익률 반환
  src/main/java/muzusi/application/account/dto/AccountDetailsDto.java
  src/main/java/muzusi/application/account/dto/AccountInfoDto.java
  src/main/java/muzusi/application/account/dto/AccountSummaryDto.java
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/application/holding/dto/HoldingInfoDto.java
  src/main/java/muzusi/application/holding/service/UserHoldingService.java
  src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
  src/main/java/muzusi/domain/holding/service/HoldingService.java
  src/main/java/muzusi/infrastructure/redis/RedisService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
  src/main/java/muzusi/presentation/holding/api/HoldingApi.java
  src/main/java/muzusi/presentation/holding/controller/HoldingController.java
Labels: feat

#88 Fix: 한국투자증권 주식 분봉 데이터 API 호출 시간 오류 수정
  src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
Labels: fix

#90 Feature: 한국투자증권 주식 체결가 웹소켓 및 클라이언트 웹소켓 연결
  src/main/java/muzusi/application/trade/dto/TradeNotificationDto.java
  src/main/java/muzusi/application/websocket/scheduler/WebSocketConnectionScheduler.java
  src/main/java/muzusi/application/websocket/service/TradeNotificationListener.java
  src/main/java/muzusi/application/websocket/service/TradeNotificationPublisher.java
  src/main/java/muzusi/domain/stock/exception/StockErrorType.java
  src/main/java/muzusi/infrastructure/config/KisWebSocketConfig.java
  src/main/java/muzusi/infrastructure/config/RedisConfig.java
  src/main/java/muzusi/infrastructure/config/WebSocketConfig.java
  src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
  src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
  src/main/java/muzusi/infrastructure/kis/KisWebSocketHandler.java
  src/main/java/muzusi/infrastructure/properties/KisProperties.java
  src/main/java/muzusi/infrastructure/redis/constant/ChannelConstant.java
  src/main/java/muzusi/presentation/websocket/inteceptor/StompInterceptor.java
  src/main/resources/application.yml
Labels: feat

#91 Feature: 계좌 일별 수익률 추가 및 반환
  src/main/java/muzusi/application/account/dto/AccountDetailsDto.java
  src/main/java/muzusi/application/account/dto/AccountProfitInfoDto.java
  src/main/java/muzusi/application/account/scheduler/AccountScheduler.java
  src/main/java/muzusi/application/account/service/AccountProfitUpdateExecutor.java
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/application/holding/service/UserHoldingService.java
  src/main/java/muzusi/domain/account/entity/AccountProfit.java
  src/main/java/muzusi/domain/account/repository/AccountProfitRepository.java
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/service/AccountProfitService.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
  src/main/java/muzusi/domain/holding/service/HoldingService.java
Labels: feat

#92 Refact: 단일 책임 원칙에 따른 한국투자증권 인증키 조회 클래스 분리
  src/main/java/muzusi/infrastructure/kis/KisAuthProvider.java
  src/main/java/muzusi/infrastructure/kis/KisOAuthClient.java
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
  src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
  src/main/java/muzusi/infrastructure/kis/KisStockClient.java
  src/main/java/muzusi/infrastructure/kis/constant/KisUrlConstant.java
  src/main/java/muzusi/infrastructure/properties/KisProperties.java
Labels: refact

#93 Refact: 한국투자증권 REST API 요청 헤더 생성 팩토리 클래스 분리
  src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
  src/main/java/muzusi/infrastructure/kis/KisRequestFactory.java
  src/main/java/muzusi/infrastructure/kis/KisStockClient.java
Labels: refact

#94 Feature: 오래된 계좌 수익률 삭제 로직 구현
  src/main/java/muzusi/application/account/scheduler/AccountScheduler.java
  src/main/java/muzusi/application/account/service/AccountProfitManager.java
  src/main/java/muzusi/domain/account/repository/AccountProfitRepository.java
  src/main/java/muzusi/domain/account/service/AccountProfitService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
Labels: feat

#95 Refact: 뉴스 삭제 로직 수정
  src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
  src/main/java/muzusi/application/news/service/NewsManagementService.java
  src/main/java/muzusi/domain/news/repository/NewsRepository.java
  src/main/java/muzusi/domain/news/service/NewsService.java
Labels: refact

#96 Feature: StompJS disconnect 메서드 deprecated에 따른 코드 변경
  src/main/java/muzusi/presentation/websocket/inteceptor/StompInterceptor.java
Labels: feat

#98 Refact: JPQL 문구 QueryDsl 적용
  .gitignore
  build.gradle
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/repository/CustomAccountRepository.java
  src/main/java/muzusi/domain/account/repository/CustomAccountRepositoryImpl.java
  src/main/java/muzusi/domain/holding/repository/CustomHoldingRepository.java
  src/main/java/muzusi/domain/holding/repository/CustomHoldingRepositoryImpl.java
  src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
  src/main/java/muzusi/domain/holding/service/HoldingService.java
  src/main/java/muzusi/infrastructure/config/QueryDslConfig.java
Labels: refact

#97 Fix: 한국투자증권 웹소켓 연결 로직 수정
  src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
Labels: fix

#99 Fix: 한국투자증권 웹소켓 세션 연결 종료 에러 수정
  src/main/java/muzusi/application/websocket/scheduler/WebSocketConnectionScheduler.java
  src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
  src/main/java/muzusi/infrastructure/kis/KisWebSocketHandler.java
Labels: fix

#100 Refact: 웹소켓 연결 관리 메서드 위치 변경
  src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
  src/main/java/muzusi/application/kis/service/KisOAuthService.java
  src/main/java/muzusi/infrastructure/kis/KisAuthService.java
  src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
  src/main/java/muzusi/infrastructure/kis/KisRequestFactory.java
  src/main/java/muzusi/infrastructure/kis/KisWebSocketHandler.java
Labels: refact

#101 Feature: 종목 검색 횟수 증가 구현
  src/main/java/muzusi/application/stock/service/StockSearchService.java
  src/main/java/muzusi/presentation/websocket/inteceptor/StompInterceptor.java
Labels: feat
