Repository Team-Digimon/muzusi-was, pull requests merged in 2025-03, with the labels that each got.

#104 Fix: KIS key 관리 오류 로직 수정
  src/main/java/muzusi/infrastructure/kis/KisAuthService.java
Labels: fix

#105 Refact: 예약 내역 데이터 관리 RDB로 변경
  src/main/java/muzusi/application/trade/dto/ReservationInfoDto.java
  src/main/java/muzusi/application/trade/service/StockTradeService.java
  src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
  src/main/java/muzusi/application/trade/service/TradeReservationProcessor.java
  src/main/java/muzusi/domain/trade/entity/TradeReservation.java
  src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
  src/main/java/muzusi/domain/trade/service/TradeReservationService.java
  src/main/java/muzusi/presentation/trade/api/TradeApi.java
  src/main/java/muzusi/presentation/trade/controller/TradeController.java
  src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java
Labels: refact

#108 Feature: 이전 계좌 조회 시, 주식 수익률 반환
  src/main/java/muzusi/application/account/dto/AccountInfoDto.java
  src/main/java/muzusi/application/account/service/UserAccountService.java
  src/main/java/muzusi/domain/account/entity/Account.java
  src/main/java/muzusi/domain/account/repository/AccountRepository.java
  src/main/java/muzusi/domain/account/repository/CustomAccountRepository.java
  src/main/java/muzusi/domain/account/repository/CustomAccountRepositoryImpl.java
  src/main/java/muzusi/domain/account/service/AccountService.java
  src/main/java/muzusi/presentation/account/api/AccountApi.java
Labels: feat

#109 Fix: JDBC 수행 중, 컬럼명 오류 수정
  src/main/java/muzusi/domain/account/entity/AccountProfit.java
  src/main/java/muzusi/domain/account/repository/CustomAccountProfitRepositoryImpl.java
Labels: fix

#110 Refact: 불필요 Entity 삭제
  src/main/java/muzusi/domain/stock/entity/PinnedStock.java
  src/main/java/muzusi/domain/stock/entity/Stock.java
  src/main/java/muzusi/domain/stock/repository/StockRepository.java
  src/main/java/muzusi/domain/stock/service/StockService.java
  src/main/java/muzusi/domain/stock/type/MarketType.java
  src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
Labels: refact

#111 Refact: default branch 변경으로 인한 CI/CD 브랜치명 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: refact

#112 Refact: 주식 분봉 차트 및 현재가 캐싱 클래스 분리
  src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
  src/main/java/muzusi/domain/stock/repository/StockMinutesCacheRepository.java
  src/main/java/muzusi/domain/stock/repository/StockPriceCacheRepository.java
  src/main/java/muzusi/domain/stock/service/StockMinutesService.java
  src/main/java/muzusi/domain/stock/service/StockPriceService.java
Labels: refact
